name: Juice Shop CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Juice Shop Docker image
      run: |
        docker build -t juice-shop .

    - name: Run Juice Shop Docker container
      run: |
        docker run --rm -d -p 3000:3000 --name juice-shop juice-shop
        # Optionally, run tests or perform additional operations here
        # Example: docker exec juice-shop npm test

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4